@ECHO OFF
type amCommands.py | find /C /V "#"
type amDB.py | find /C /V "#"
type amDefines.py | find /C /V "#"
type amLog.py | find /C /V "#"
type amParser.py | find /C /V "#"
type amRace.py | find /C /V "#"
type amRooms.py | find /C /V "#"
type amUtils.py | find /C /V "#"
type ArenaMUD.py | find /C /V "#"
